# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window3.ui'
#
# Created: Sat Feb 21 16:10:00 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(773, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_34 = QtGui.QLabel(self.groupBox)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 2, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_3.addWidget(self.lineEdit_14, 3, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 2, 3, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_10.setMaximum(100)
        self.spinBox_10.setSingleStep(5)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_3.addWidget(self.spinBox_10, 2, 4, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_7, 2, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_3.addWidget(self.lineEdit_11, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_5, 0, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 0, 3, 1, 1)
        self.comboBox_13 = QtGui.QComboBox(self.groupBox)
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_13, 0, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 2, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_6)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 2, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout.addWidget(self.lineEdit_15, 4, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_6)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_6)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout.addWidget(self.lineEdit_18, 2, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_6)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 3, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 4, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 1, 0, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout.addWidget(self.lineEdit_17, 1, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 1, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_6)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 5, 1, 1)
        self.comboBox_16 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_16.setObjectName(_fromUtf8("comboBox_16"))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.comboBox_16.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_16, 1, 5, 1, 1)
        self.comboBox_17 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_17.setObjectName(_fromUtf8("comboBox_17"))
        self.comboBox_17.addItem(_fromUtf8(""))
        self.comboBox_17.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_17, 2, 5, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 3, 5, 1, 1)
        self.comboBox_14 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_14, 4, 5, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_8.setMaximum(100)
        self.spinBox_8.setSingleStep(5)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_2.addWidget(self.spinBox_8, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 1, 1, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_2.addWidget(self.spinBox_9, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_18 = QtGui.QLabel(self.groupBox_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_10, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_4.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_9, 0, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_4.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 1)
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_11, 2, 2, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_4.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_8, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 1, 0, 1, 1)
        self.comboBox_15 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_15.setObjectName(_fromUtf8("comboBox_15"))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.comboBox_15.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_15, 1, 2, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_6.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.comboBox_27 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_27.setObjectName(_fromUtf8("comboBox_27"))
        self.comboBox_27.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_27, 2, 2, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_5.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_6, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_5.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_5.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_53 = QtGui.QLabel(self.groupBox_9)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_7.addWidget(self.label_53, 0, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_7.addWidget(self.lineEdit_13, 1, 1, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_7.addWidget(self.lineEdit_20, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_9)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_9)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.gridLayout_7.addWidget(self.lineEdit_28, 0, 1, 1, 1)
        self.comboBox_18 = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_18.setObjectName(_fromUtf8("comboBox_18"))
        self.comboBox_18.addItem(_fromUtf8(""))
        self.comboBox_18.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_18, 2, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.segment_info_grid1 = QtGui.QGridLayout()
        self.segment_info_grid1.setObjectName(_fromUtf8("segment_info_grid1"))
        self.label_43 = QtGui.QLabel(self.groupBox_10)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.segment_info_grid1.addWidget(self.label_43, 0, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.segment_info_grid1.addWidget(self.lineEdit_21, 1, 1, 1, 1)
        self.comboBox_19 = QtGui.QComboBox(self.groupBox_10)
        self.comboBox_19.setObjectName(_fromUtf8("comboBox_19"))
        self.comboBox_19.addItem(_fromUtf8(""))
        self.comboBox_19.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.comboBox_19, 1, 2, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.segment_info_grid1.addWidget(self.lineEdit_22, 2, 1, 1, 1)
        self.comboBox_12 = QtGui.QComboBox(self.groupBox_10)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.comboBox_12, 0, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_10)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.segment_info_grid1.addWidget(self.label_45, 1, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_10)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.segment_info_grid1.addWidget(self.label_46, 2, 0, 1, 1)
        self.comboBox_20 = QtGui.QComboBox(self.groupBox_10)
        self.comboBox_20.setObjectName(_fromUtf8("comboBox_20"))
        self.comboBox_20.addItem(_fromUtf8(""))
        self.comboBox_20.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.comboBox_20, 2, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_10)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.segment_info_grid1.addWidget(self.label_47, 3, 0, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.segment_info_grid1.addWidget(self.lineEdit_23, 3, 1, 1, 1)
        self.comboBox_21 = QtGui.QComboBox(self.groupBox_10)
        self.comboBox_21.setObjectName(_fromUtf8("comboBox_21"))
        self.comboBox_21.addItem(_fromUtf8(""))
        self.comboBox_21.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.comboBox_21, 3, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.segment_info_grid1)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.pushButton = QtGui.QPushButton(self.groupBox_10)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_50.addWidget(self.pushButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_50)
        self.verticalLayout_9.addWidget(self.groupBox_10)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_9)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_9.addWidget(self.graphicsView)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_54 = QtGui.QLabel(self.groupBox_11)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_8.addWidget(self.label_54, 0, 0, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_8.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_8.addWidget(self.lineEdit_24, 2, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_11)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_8.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_11)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 1, 0, 1, 1)
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.gridLayout_8.addWidget(self.lineEdit_29, 0, 1, 1, 1)
        self.comboBox_22 = QtGui.QComboBox(self.groupBox_11)
        self.comboBox_22.setObjectName(_fromUtf8("comboBox_22"))
        self.comboBox_22.addItem(_fromUtf8(""))
        self.comboBox_22.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_22, 2, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_8)
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_11)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.segment_info_grid1_2 = QtGui.QGridLayout()
        self.segment_info_grid1_2.setObjectName(_fromUtf8("segment_info_grid1_2"))
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.segment_info_grid1_2.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        self.comboBox_23 = QtGui.QComboBox(self.groupBox_12)
        self.comboBox_23.setObjectName(_fromUtf8("comboBox_23"))
        self.comboBox_23.addItem(_fromUtf8(""))
        self.comboBox_23.addItem(_fromUtf8(""))
        self.segment_info_grid1_2.addWidget(self.comboBox_23, 1, 2, 1, 1)
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.segment_info_grid1_2.addWidget(self.lineEdit_26, 2, 1, 1, 1)
        self.comboBox_24 = QtGui.QComboBox(self.groupBox_12)
        self.comboBox_24.setObjectName(_fromUtf8("comboBox_24"))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.comboBox_24.addItem(_fromUtf8(""))
        self.segment_info_grid1_2.addWidget(self.comboBox_24, 0, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_12)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.segment_info_grid1_2.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_12)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.segment_info_grid1_2.addWidget(self.label_51, 2, 0, 1, 1)
        self.comboBox_25 = QtGui.QComboBox(self.groupBox_12)
        self.comboBox_25.setObjectName(_fromUtf8("comboBox_25"))
        self.comboBox_25.addItem(_fromUtf8(""))
        self.comboBox_25.addItem(_fromUtf8(""))
        self.segment_info_grid1_2.addWidget(self.comboBox_25, 2, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_12)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.segment_info_grid1_2.addWidget(self.label_52, 3, 0, 1, 1)
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.segment_info_grid1_2.addWidget(self.lineEdit_27, 3, 1, 1, 1)
        self.comboBox_26 = QtGui.QComboBox(self.groupBox_12)
        self.comboBox_26.setObjectName(_fromUtf8("comboBox_26"))
        self.comboBox_26.addItem(_fromUtf8(""))
        self.comboBox_26.addItem(_fromUtf8(""))
        self.segment_info_grid1_2.addWidget(self.comboBox_26, 3, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_12)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.segment_info_grid1_2.addWidget(self.label_49, 0, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.segment_info_grid1_2)
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_12)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_51.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_51)
        self.verticalLayout_11.addWidget(self.groupBox_12)
        self.graphicsView_2 = QtGui.QGraphicsView(self.groupBox_11)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_11.addWidget(self.graphicsView_2)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 110, 235, 240))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.spinBox = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_11.addWidget(self.spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_27.addWidget(self.label_20)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_7.setMaximum(3)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_27.addWidget(self.spinBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_16.addWidget(self.label_6)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_2.setMinimum(0)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_13.addWidget(self.spinBox_2)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_3.setMinimum(0)
        self.spinBox_3.setMaximum(12)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_13.addWidget(self.spinBox_3)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_4.setMinimum(0)
        self.spinBox_4.setMaximum(12)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_13.addWidget(self.spinBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_5.setMinimum(0)
        self.spinBox_5.setMaximum(5)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_18.addWidget(self.spinBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_6.setMaximum(3)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_8.addWidget(self.spinBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(210, 120, 102, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(318, 120, 84, 20))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Performance", None))
        self.label_34.setText(_translate("MainWindow", "C", None))
        self.label_16.setText(_translate("MainWindow", "Rate of Climb:", None))
        self.label_23.setText(_translate("MainWindow", "Cruise Mach No.:", None))
        self.label_33.setText(_translate("MainWindow", "for ISA+", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "m/s", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "ft/min", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_4.setText(_translate("MainWindow", "Service Ceiling:", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "km", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "mi", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "nm", None))
        self.label_3.setText(_translate("MainWindow", "Design Range:", None))
        self.label_32.setText(_translate("MainWindow", "for payload: ", None))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "lb", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Take-off and landing", None))
        self.label_41.setText(_translate("MainWindow", "Landing Distance (Land):   ", None))
        self.label_2.setText(_translate("MainWindow", "Landing Distance (Water): ", None))
        self.label_24.setText(_translate("MainWindow", "Max. Runway altitude:       ", None))
        self.label.setText(_translate("MainWindow", "Take-off Distance (Land):  ", None))
        self.label_38.setText(_translate("MainWindow", "Take-off Distance (Water):", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "m ", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "ft ", None))
        self.comboBox_16.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_16.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "m ", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "ft ", None))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_27.setText(_translate("MainWindow", "ISA+", None))
        self.label_25.setText(_translate("MainWindow", "Atmospheric compliance at MSL:       ", None))
        self.label_28.setText(_translate("MainWindow", "C", None))
        self.label_30.setText(_translate("MainWindow", "Atmospheric compliance at altitude m :", None))
        self.label_31.setText(_translate("MainWindow", "ISA+", None))
        self.label_29.setText(_translate("MainWindow", "C", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Turn Rate", None))
        self.label_18.setText(_translate("MainWindow", "Instantaneous: ", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.label_19.setText(_translate("MainWindow", "Sustained:         ", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.label_21.setText(_translate("MainWindow", "Bank angle:       ", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "deg  ", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "rad", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Operational", None))
        self.label_17.setText(_translate("MainWindow", "Aviation Regulations:", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "FAR 23", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "FAR 25", None))
        self.label_35.setText(_translate("MainWindow", "Fuel Reserve range:", None))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "km", None))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "nm", None))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "mi", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Payload", None))
        self.comboBox_27.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "kg", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "lb", None))
        self.label_8.setText(_translate("MainWindow", "Cargo Weight:", None))
        self.label_9.setText(_translate("MainWindow", "Total Payload Weight:  ", None))
        self.label_7.setText(_translate("MainWindow", "Number of Passengers:", None))
        self.pushButton_3.setText(_translate("MainWindow", "Set Requirements", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Requirements", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Mission 1", None))
        self.label_53.setText(_translate("MainWindow", "Mission Name: ", None))
        self.label_44.setText(_translate("MainWindow", "Altitude at beginning of mission:", None))
        self.label_22.setText(_translate("MainWindow", "Number of mission segments:", None))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "ft", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Segment info", None))
        self.label_43.setText(_translate("MainWindow", "Type of Segment", None))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "Takeoff", None))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "Climb", None))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "Cruise", None))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "Loiter", None))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "Descent", None))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "Landing", None))
        self.label_45.setText(_translate("MainWindow", "Range of segment:  ", None))
        self.label_46.setText(_translate("MainWindow", "Height of segment:  ", None))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_47.setText(_translate("MainWindow", "Time duration        ", None))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "hr", None))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "min", None))
        self.pushButton.setText(_translate("MainWindow", "Add Segment", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Mission 2", None))
        self.label_54.setText(_translate("MainWindow", "Mission Name: ", None))
        self.label_48.setText(_translate("MainWindow", "Altitude at beginning of mission:", None))
        self.label_26.setText(_translate("MainWindow", "Number of mission segments:", None))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "ft", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Segment info", None))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_24.setItemText(0, _translate("MainWindow", "Takeoff", None))
        self.comboBox_24.setItemText(1, _translate("MainWindow", "Climb", None))
        self.comboBox_24.setItemText(2, _translate("MainWindow", "Cruise", None))
        self.comboBox_24.setItemText(3, _translate("MainWindow", "Loiter", None))
        self.comboBox_24.setItemText(4, _translate("MainWindow", "Descent", None))
        self.comboBox_24.setItemText(5, _translate("MainWindow", "Landing", None))
        self.label_50.setText(_translate("MainWindow", "Range of segment:  ", None))
        self.label_51.setText(_translate("MainWindow", "Height of segment:  ", None))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_52.setText(_translate("MainWindow", "Time duration        ", None))
        self.comboBox_26.setItemText(0, _translate("MainWindow", "hr", None))
        self.comboBox_26.setItemText(1, _translate("MainWindow", "min", None))
        self.label_49.setText(_translate("MainWindow", "Type of Segment", None))
        self.pushButton_2.setText(_translate("MainWindow", "Add Segment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Mission Definition", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cabin configuration", None))
        self.label_10.setText(_translate("MainWindow", "Number of classes: ", None))
        self.label_20.setText(_translate("MainWindow", "Number of aisles:                        ", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Average Seats abreast", None))
        self.label_6.setText(_translate("MainWindow", "Class I", None))
        self.label_11.setText(_translate("MainWindow", "Class II", None))
        self.label_12.setText(_translate("MainWindow", "Class III", None))
        self.label_13.setText(_translate("MainWindow", "Satisfying the number of paassengers", None))
        self.label_14.setText(_translate("MainWindow", "Number of Lavatories: ", None))
        self.label_5.setText(_translate("MainWindow", "Number of Galleys: ", None))
        self.label_15.setText(_translate("MainWindow", "Type of Aircraft:", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Passenger", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Cargo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Aircraft Configuration", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Design Space", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Historic Data", None))

