# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window3.ui'
#
# Created: Tue Mar 17 19:44:37 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(769, 638)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.req_tab = QtGui.QWidget()
        self.req_tab.setObjectName(_fromUtf8("req_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.req_tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.performance_gb = QtGui.QGroupBox(self.req_tab)
        self.performance_gb.setObjectName(_fromUtf8("performance_gb"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.performance_gb)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.roc_cels = QtGui.QLabel(self.performance_gb)
        self.roc_cels.setObjectName(_fromUtf8("roc_cels"))
        self.gridLayout_3.addWidget(self.roc_cels, 2, 5, 1, 1)
        self.roc_lab = QtGui.QLabel(self.performance_gb)
        self.roc_lab.setObjectName(_fromUtf8("roc_lab"))
        self.gridLayout_3.addWidget(self.roc_lab, 2, 0, 1, 1)
        self.cruise_m_lab = QtGui.QLabel(self.performance_gb)
        self.cruise_m_lab.setObjectName(_fromUtf8("cruise_m_lab"))
        self.gridLayout_3.addWidget(self.cruise_m_lab, 3, 0, 1, 1)
        self.cruise_m_inp = QtGui.QLineEdit(self.performance_gb)
        self.cruise_m_inp.setObjectName(_fromUtf8("cruise_m_inp"))
        self.gridLayout_3.addWidget(self.cruise_m_inp, 3, 1, 1, 1)
        self.roc_isa = QtGui.QLabel(self.performance_gb)
        self.roc_isa.setObjectName(_fromUtf8("roc_isa"))
        self.gridLayout_3.addWidget(self.roc_isa, 2, 3, 1, 1)
        self.roc_isa_t_sb = QtGui.QSpinBox(self.performance_gb)
        self.roc_isa_t_sb.setMaximum(100)
        self.roc_isa_t_sb.setSingleStep(5)
        self.roc_isa_t_sb.setObjectName(_fromUtf8("roc_isa_t_sb"))
        self.gridLayout_3.addWidget(self.roc_isa_t_sb, 2, 4, 1, 1)
        self.roc_mpers_comb = QtGui.QComboBox(self.performance_gb)
        self.roc_mpers_comb.setMinimumSize(QtCore.QSize(54, 0))
        self.roc_mpers_comb.setObjectName(_fromUtf8("roc_mpers_comb"))
        self.roc_mpers_comb.addItem(_fromUtf8(""))
        self.roc_mpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.roc_mpers_comb, 2, 2, 1, 1)
        self.serv_ceil_inp = QtGui.QLineEdit(self.performance_gb)
        self.serv_ceil_inp.setObjectName(_fromUtf8("serv_ceil_inp"))
        self.gridLayout_3.addWidget(self.serv_ceil_inp, 1, 1, 1, 1)
        self.roc_inp = QtGui.QLineEdit(self.performance_gb)
        self.roc_inp.setObjectName(_fromUtf8("roc_inp"))
        self.gridLayout_3.addWidget(self.roc_inp, 2, 1, 1, 1)
        self.ser_ceil_m_comb = QtGui.QComboBox(self.performance_gb)
        self.ser_ceil_m_comb.setObjectName(_fromUtf8("ser_ceil_m_comb"))
        self.ser_ceil_m_comb.addItem(_fromUtf8(""))
        self.ser_ceil_m_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ser_ceil_m_comb, 1, 2, 1, 1)
        self.des_rang_payload_inp = QtGui.QLineEdit(self.performance_gb)
        self.des_rang_payload_inp.setObjectName(_fromUtf8("des_rang_payload_inp"))
        self.gridLayout_3.addWidget(self.des_rang_payload_inp, 0, 4, 1, 1)
        self.serv_ceil_lab = QtGui.QLabel(self.performance_gb)
        self.serv_ceil_lab.setObjectName(_fromUtf8("serv_ceil_lab"))
        self.gridLayout_3.addWidget(self.serv_ceil_lab, 1, 0, 1, 1)
        self.des_rang_km_comb = QtGui.QComboBox(self.performance_gb)
        self.des_rang_km_comb.setObjectName(_fromUtf8("des_rang_km_comb"))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.des_rang_km_comb, 0, 2, 1, 1)
        self.des_rang_inp = QtGui.QLineEdit(self.performance_gb)
        self.des_rang_inp.setObjectName(_fromUtf8("des_rang_inp"))
        self.gridLayout_3.addWidget(self.des_rang_inp, 0, 1, 1, 1)
        self.des_rang_lab = QtGui.QLabel(self.performance_gb)
        self.des_rang_lab.setObjectName(_fromUtf8("des_rang_lab"))
        self.gridLayout_3.addWidget(self.des_rang_lab, 0, 0, 1, 1)
        self.des_rang_payload_lab = QtGui.QLabel(self.performance_gb)
        self.des_rang_payload_lab.setObjectName(_fromUtf8("des_rang_payload_lab"))
        self.gridLayout_3.addWidget(self.des_rang_payload_lab, 0, 3, 1, 1)
        self.des_rang_payload_kg_comb = QtGui.QComboBox(self.performance_gb)
        self.des_rang_payload_kg_comb.setObjectName(_fromUtf8("des_rang_payload_kg_comb"))
        self.des_rang_payload_kg_comb.addItem(_fromUtf8(""))
        self.des_rang_payload_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.des_rang_payload_kg_comb, 0, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.to_lan_gb = QtGui.QGroupBox(self.performance_gb)
        self.to_lan_gb.setObjectName(_fromUtf8("to_lan_gb"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.to_lan_gb)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_40 = QtGui.QLabel(self.to_lan_gb)
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 2, 1, 1, 1)
        self.lan_land_lab = QtGui.QLabel(self.to_lan_gb)
        self.lan_land_lab.setObjectName(_fromUtf8("lan_land_lab"))
        self.gridLayout.addWidget(self.lan_land_lab, 2, 0, 1, 1)
        self.max_run_alt_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.max_run_alt_inp.setObjectName(_fromUtf8("max_run_alt_inp"))
        self.gridLayout.addWidget(self.max_run_alt_inp, 4, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.to_lan_gb)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 3, 1, 1, 1)
        self.lan_water_lab = QtGui.QLabel(self.to_lan_gb)
        self.lan_water_lab.setObjectName(_fromUtf8("lan_water_lab"))
        self.gridLayout.addWidget(self.lan_water_lab, 3, 0, 1, 1)
        self.lan_land_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.lan_land_inp.setObjectName(_fromUtf8("lan_land_inp"))
        self.gridLayout.addWidget(self.lan_land_inp, 2, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.to_lan_gb)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 0, 1, 1, 1)
        self.lan_water_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.lan_water_inp.setObjectName(_fromUtf8("lan_water_inp"))
        self.gridLayout.addWidget(self.lan_water_inp, 3, 4, 1, 1)
        self.max_run_alt_lab = QtGui.QLabel(self.to_lan_gb)
        self.max_run_alt_lab.setObjectName(_fromUtf8("max_run_alt_lab"))
        self.gridLayout.addWidget(self.max_run_alt_lab, 4, 0, 1, 1)
        self.tod_land_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.tod_land_inp.setObjectName(_fromUtf8("tod_land_inp"))
        self.gridLayout.addWidget(self.tod_land_inp, 0, 4, 1, 1)
        self.tod_land_lab = QtGui.QLabel(self.to_lan_gb)
        self.tod_land_lab.setObjectName(_fromUtf8("tod_land_lab"))
        self.gridLayout.addWidget(self.tod_land_lab, 0, 0, 1, 1)
        self.tod_water_lab = QtGui.QLabel(self.to_lan_gb)
        self.tod_water_lab.setObjectName(_fromUtf8("tod_water_lab"))
        self.gridLayout.addWidget(self.tod_water_lab, 1, 0, 1, 1)
        self.tod_water_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.tod_water_inp.setObjectName(_fromUtf8("tod_water_inp"))
        self.gridLayout.addWidget(self.tod_water_inp, 1, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.to_lan_gb)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 1, 1, 1, 1)
        self.tod_lan_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.tod_lan_m_comb.setObjectName(_fromUtf8("tod_lan_m_comb"))
        self.tod_lan_m_comb.addItem(_fromUtf8(""))
        self.tod_lan_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.tod_lan_m_comb, 0, 5, 1, 1)
        self.tod_water_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.tod_water_m_comb.setObjectName(_fromUtf8("tod_water_m_comb"))
        self.tod_water_m_comb.addItem(_fromUtf8(""))
        self.tod_water_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.tod_water_m_comb, 1, 5, 1, 1)
        self.lan_land_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.lan_land_m_comb.setObjectName(_fromUtf8("lan_land_m_comb"))
        self.lan_land_m_comb.addItem(_fromUtf8(""))
        self.lan_land_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.lan_land_m_comb, 2, 5, 1, 1)
        self.lan_water_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.lan_water_m_comb.setObjectName(_fromUtf8("lan_water_m_comb"))
        self.lan_water_m_comb.addItem(_fromUtf8(""))
        self.lan_water_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.lan_water_m_comb, 3, 5, 1, 1)
        self.max_run_alt_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.max_run_alt_m_comb.setMinimumSize(QtCore.QSize(36, 0))
        self.max_run_alt_m_comb.setObjectName(_fromUtf8("max_run_alt_m_comb"))
        self.max_run_alt_m_comb.addItem(_fromUtf8(""))
        self.max_run_alt_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.max_run_alt_m_comb, 4, 5, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.msl_isa = QtGui.QLabel(self.to_lan_gb)
        self.msl_isa.setObjectName(_fromUtf8("msl_isa"))
        self.gridLayout_2.addWidget(self.msl_isa, 0, 1, 1, 1)
        self.atm_msl_lab = QtGui.QLabel(self.to_lan_gb)
        self.atm_msl_lab.setObjectName(_fromUtf8("atm_msl_lab"))
        self.gridLayout_2.addWidget(self.atm_msl_lab, 0, 0, 1, 1)
        self.run_msl_isa_t_sb = QtGui.QSpinBox(self.to_lan_gb)
        self.run_msl_isa_t_sb.setMaximum(100)
        self.run_msl_isa_t_sb.setSingleStep(5)
        self.run_msl_isa_t_sb.setObjectName(_fromUtf8("run_msl_isa_t_sb"))
        self.gridLayout_2.addWidget(self.run_msl_isa_t_sb, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.to_lan_gb)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.atm_alt_lab = QtGui.QLabel(self.to_lan_gb)
        self.atm_alt_lab.setObjectName(_fromUtf8("atm_alt_lab"))
        self.gridLayout_2.addWidget(self.atm_alt_lab, 1, 0, 1, 1)
        self.alt_isa = QtGui.QLabel(self.to_lan_gb)
        self.alt_isa.setObjectName(_fromUtf8("alt_isa"))
        self.gridLayout_2.addWidget(self.alt_isa, 1, 1, 1, 1)
        self.run_alt_isa_t_sb = QtGui.QSpinBox(self.to_lan_gb)
        self.run_alt_isa_t_sb.setMaximum(100)
        self.run_alt_isa_t_sb.setSingleStep(5)
        self.run_alt_isa_t_sb.setObjectName(_fromUtf8("run_alt_isa_t_sb"))
        self.gridLayout_2.addWidget(self.run_alt_isa_t_sb, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.to_lan_gb)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_10.addWidget(self.to_lan_gb)
        self.turn_rate_gb = QtGui.QGroupBox(self.performance_gb)
        self.turn_rate_gb.setObjectName(_fromUtf8("turn_rate_gb"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.turn_rate_gb)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.inst_lab = QtGui.QLabel(self.turn_rate_gb)
        self.inst_lab.setObjectName(_fromUtf8("inst_lab"))
        self.gridLayout_4.addWidget(self.inst_lab, 0, 0, 1, 1)
        self.sus_degpers_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.sus_degpers_comb.setObjectName(_fromUtf8("sus_degpers_comb"))
        self.sus_degpers_comb.addItem(_fromUtf8(""))
        self.sus_degpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.sus_degpers_comb, 1, 2, 1, 1)
        self.sus_lab = QtGui.QLabel(self.turn_rate_gb)
        self.sus_lab.setObjectName(_fromUtf8("sus_lab"))
        self.gridLayout_4.addWidget(self.sus_lab, 1, 0, 1, 1)
        self.inst_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.inst_inp.setObjectName(_fromUtf8("inst_inp"))
        self.gridLayout_4.addWidget(self.inst_inp, 0, 1, 1, 1)
        self.inst_degpers_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.inst_degpers_comb.setMinimumSize(QtCore.QSize(53, 0))
        self.inst_degpers_comb.setObjectName(_fromUtf8("inst_degpers_comb"))
        self.inst_degpers_comb.addItem(_fromUtf8(""))
        self.inst_degpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.inst_degpers_comb, 0, 2, 1, 1)
        self.sus_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.sus_inp.setObjectName(_fromUtf8("sus_inp"))
        self.gridLayout_4.addWidget(self.sus_inp, 1, 1, 1, 1)
        self.bank_ang_lab = QtGui.QLabel(self.turn_rate_gb)
        self.bank_ang_lab.setObjectName(_fromUtf8("bank_ang_lab"))
        self.gridLayout_4.addWidget(self.bank_ang_lab, 2, 0, 1, 1)
        self.bank_ang_deg_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.bank_ang_deg_comb.setObjectName(_fromUtf8("bank_ang_deg_comb"))
        self.bank_ang_deg_comb.addItem(_fromUtf8(""))
        self.bank_ang_deg_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.bank_ang_deg_comb, 2, 2, 1, 1)
        self.bank_ang_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.bank_ang_inp.setObjectName(_fromUtf8("bank_ang_inp"))
        self.gridLayout_4.addWidget(self.bank_ang_inp, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout_10.addWidget(self.turn_rate_gb)
        self.verticalLayout_6.addWidget(self.performance_gb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.operational_gb = QtGui.QGroupBox(self.req_tab)
        self.operational_gb.setObjectName(_fromUtf8("operational_gb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.operational_gb)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.reg_lab = QtGui.QLabel(self.operational_gb)
        self.reg_lab.setObjectName(_fromUtf8("reg_lab"))
        self.gridLayout_6.addWidget(self.reg_lab, 0, 0, 1, 1)
        self.reg_comb = QtGui.QComboBox(self.operational_gb)
        self.reg_comb.setObjectName(_fromUtf8("reg_comb"))
        self.reg_comb.addItem(_fromUtf8(""))
        self.reg_comb.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.reg_comb, 0, 1, 1, 1)
        self.fuel_res_lab = QtGui.QLabel(self.operational_gb)
        self.fuel_res_lab.setObjectName(_fromUtf8("fuel_res_lab"))
        self.gridLayout_6.addWidget(self.fuel_res_lab, 1, 0, 1, 1)
        self.fuel_res_km_comb = QtGui.QComboBox(self.operational_gb)
        self.fuel_res_km_comb.setMinimumSize(QtCore.QSize(40, 0))
        self.fuel_res_km_comb.setObjectName(_fromUtf8("fuel_res_km_comb"))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.fuel_res_km_comb, 1, 2, 1, 1)
        self.fuel_res_inp = QtGui.QLineEdit(self.operational_gb)
        self.fuel_res_inp.setObjectName(_fromUtf8("fuel_res_inp"))
        self.gridLayout_6.addWidget(self.fuel_res_inp, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.payload_gb = QtGui.QGroupBox(self.operational_gb)
        self.payload_gb.setObjectName(_fromUtf8("payload_gb"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.payload_gb)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pay_wt_kg_comb = QtGui.QComboBox(self.payload_gb)
        self.pay_wt_kg_comb.setMinimumSize(QtCore.QSize(37, 0))
        self.pay_wt_kg_comb.setObjectName(_fromUtf8("pay_wt_kg_comb"))
        self.pay_wt_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pay_wt_kg_comb, 2, 2, 1, 1)
        self.cargo_kg_comb = QtGui.QComboBox(self.payload_gb)
        self.cargo_kg_comb.setObjectName(_fromUtf8("cargo_kg_comb"))
        self.cargo_kg_comb.addItem(_fromUtf8(""))
        self.cargo_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cargo_kg_comb, 1, 2, 1, 1)
        self.cargo_lab = QtGui.QLabel(self.payload_gb)
        self.cargo_lab.setObjectName(_fromUtf8("cargo_lab"))
        self.gridLayout_5.addWidget(self.cargo_lab, 1, 0, 1, 1)
        self.cargo_inp = QtGui.QLineEdit(self.payload_gb)
        self.cargo_inp.setObjectName(_fromUtf8("cargo_inp"))
        self.gridLayout_5.addWidget(self.cargo_inp, 1, 1, 1, 1)
        self.pay_wt_lab = QtGui.QLabel(self.payload_gb)
        self.pay_wt_lab.setObjectName(_fromUtf8("pay_wt_lab"))
        self.gridLayout_5.addWidget(self.pay_wt_lab, 2, 0, 1, 1)
        self.pass_inp = QtGui.QLineEdit(self.payload_gb)
        self.pass_inp.setObjectName(_fromUtf8("pass_inp"))
        self.gridLayout_5.addWidget(self.pass_inp, 0, 1, 1, 1)
        self.pass_lab = QtGui.QLabel(self.payload_gb)
        self.pass_lab.setObjectName(_fromUtf8("pass_lab"))
        self.gridLayout_5.addWidget(self.pass_lab, 0, 0, 1, 1)
        self.pay_wt_inplab = QtGui.QLabel(self.payload_gb)
        self.pay_wt_inplab.setObjectName(_fromUtf8("pay_wt_inplab"))
        self.gridLayout_5.addWidget(self.pay_wt_inplab, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addWidget(self.payload_gb)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.engine_lab = QtGui.QLabel(self.operational_gb)
        self.engine_lab.setObjectName(_fromUtf8("engine_lab"))
        self.gridLayout_10.addWidget(self.engine_lab, 0, 0, 1, 1)
        self.engine_inp = QtGui.QLineEdit(self.operational_gb)
        self.engine_inp.setObjectName(_fromUtf8("engine_inp"))
        self.gridLayout_10.addWidget(self.engine_inp, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.set_req_push = QtGui.QPushButton(self.operational_gb)
        self.set_req_push.setObjectName(_fromUtf8("set_req_push"))
        self.verticalLayout_2.addWidget(self.set_req_push)
        self.horizontalLayout_3.addWidget(self.operational_gb)
        self.tabWidget.addTab(self.req_tab, _fromUtf8(""))
        self.mission_tab = QtGui.QWidget()
        self.mission_tab.setObjectName(_fromUtf8("mission_tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.mission_tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.miss_select_comb = QtGui.QComboBox(self.mission_tab)
        self.miss_select_comb.setObjectName(_fromUtf8("miss_select_comb"))
        self.miss_select_comb.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.miss_select_comb)
        self.miss_add_push = QtGui.QPushButton(self.mission_tab)
        self.miss_add_push.setObjectName(_fromUtf8("miss_add_push"))
        self.horizontalLayout_2.addWidget(self.miss_add_push)
        self.miss_rem_push = QtGui.QPushButton(self.mission_tab)
        self.miss_rem_push.setObjectName(_fromUtf8("miss_rem_push"))
        self.horizontalLayout_2.addWidget(self.miss_rem_push)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.alt_beg_seg_m_comb = QtGui.QComboBox(self.mission_tab)
        self.alt_beg_seg_m_comb.setObjectName(_fromUtf8("alt_beg_seg_m_comb"))
        self.alt_beg_seg_m_comb.addItem(_fromUtf8(""))
        self.alt_beg_seg_m_comb.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.alt_beg_seg_m_comb, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 3, 1, 1)
        self.miss_nam_lab = QtGui.QLabel(self.mission_tab)
        self.miss_nam_lab.setObjectName(_fromUtf8("miss_nam_lab"))
        self.gridLayout_7.addWidget(self.miss_nam_lab, 0, 0, 1, 1)
        self.alt_beg_inp = QtGui.QLineEdit(self.mission_tab)
        self.alt_beg_inp.setObjectName(_fromUtf8("alt_beg_inp"))
        self.gridLayout_7.addWidget(self.alt_beg_inp, 1, 1, 1, 1)
        self.miss_nam_inp = QtGui.QLineEdit(self.mission_tab)
        self.miss_nam_inp.setObjectName(_fromUtf8("miss_nam_inp"))
        self.gridLayout_7.addWidget(self.miss_nam_inp, 0, 1, 1, 1)
        self.alt_beg_lab = QtGui.QLabel(self.mission_tab)
        self.alt_beg_lab.setObjectName(_fromUtf8("alt_beg_lab"))
        self.gridLayout_7.addWidget(self.alt_beg_lab, 1, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_7)
        self.seg_inf_gb = QtGui.QGroupBox(self.mission_tab)
        self.seg_inf_gb.setObjectName(_fromUtf8("seg_inf_gb"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.seg_inf_gb)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.segment_info_grid1 = QtGui.QGridLayout()
        self.segment_info_grid1.setObjectName(_fromUtf8("segment_info_grid1"))
        self.typ_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.typ_seg_lab.setObjectName(_fromUtf8("typ_seg_lab"))
        self.segment_info_grid1.addWidget(self.typ_seg_lab, 0, 0, 1, 1)
        self.ht_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.ht_seg_inp.setObjectName(_fromUtf8("ht_seg_inp"))
        self.segment_info_grid1.addWidget(self.ht_seg_inp, 2, 1, 1, 1)
        self.rang_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.rang_seg_lab.setObjectName(_fromUtf8("rang_seg_lab"))
        self.segment_info_grid1.addWidget(self.rang_seg_lab, 1, 0, 1, 1)
        self.ht_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.ht_seg_lab.setObjectName(_fromUtf8("ht_seg_lab"))
        self.segment_info_grid1.addWidget(self.ht_seg_lab, 2, 0, 1, 1)
        self.typ_seg_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.typ_seg_comb.setObjectName(_fromUtf8("typ_seg_comb"))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.typ_seg_comb, 0, 1, 1, 1)
        self.time_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.time_seg_lab.setObjectName(_fromUtf8("time_seg_lab"))
        self.segment_info_grid1.addWidget(self.time_seg_lab, 3, 0, 1, 1)
        self.time_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.time_seg_inp.setObjectName(_fromUtf8("time_seg_inp"))
        self.segment_info_grid1.addWidget(self.time_seg_inp, 3, 1, 1, 1)
        self.rang_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.rang_seg_inp.setObjectName(_fromUtf8("rang_seg_inp"))
        self.segment_info_grid1.addWidget(self.rang_seg_inp, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.segment_info_grid1.addItem(spacerItem6, 0, 3, 1, 1)
        self.rang_seg_m_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.rang_seg_m_comb.setObjectName(_fromUtf8("rang_seg_m_comb"))
        self.rang_seg_m_comb.addItem(_fromUtf8(""))
        self.rang_seg_m_comb.addItem(_fromUtf8(""))
        self.rang_seg_m_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.rang_seg_m_comb, 1, 2, 1, 1)
        self.ht_seg_m_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.ht_seg_m_comb.setObjectName(_fromUtf8("ht_seg_m_comb"))
        self.ht_seg_m_comb.addItem(_fromUtf8(""))
        self.ht_seg_m_comb.addItem(_fromUtf8(""))
        self.ht_seg_m_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.ht_seg_m_comb, 2, 2, 1, 1)
        self.time_seg_hr_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.time_seg_hr_comb.setObjectName(_fromUtf8("time_seg_hr_comb"))
        self.time_seg_hr_comb.addItem(_fromUtf8(""))
        self.time_seg_hr_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.time_seg_hr_comb, 3, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.segment_info_grid1)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.add_seg_push = QtGui.QPushButton(self.seg_inf_gb)
        self.add_seg_push.setObjectName(_fromUtf8("add_seg_push"))
        self.horizontalLayout_50.addWidget(self.add_seg_push)
        self.rem_seg_push = QtGui.QPushButton(self.seg_inf_gb)
        self.rem_seg_push.setObjectName(_fromUtf8("rem_seg_push"))
        self.horizontalLayout_50.addWidget(self.rem_seg_push)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem7)
        self.verticalLayout_12.addLayout(self.horizontalLayout_50)
        self.verticalLayout_11.addWidget(self.seg_inf_gb)
        self.mission_graphics = QtGui.QGraphicsView(self.mission_tab)
        self.mission_graphics.setObjectName(_fromUtf8("mission_graphics"))
        self.verticalLayout_11.addWidget(self.mission_graphics)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.ana_miss_push = QtGui.QPushButton(self.mission_tab)
        self.ana_miss_push.setObjectName(_fromUtf8("ana_miss_push"))
        self.horizontalLayout_4.addWidget(self.ana_miss_push)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.mission_tab, _fromUtf8(""))
        self.design_tab = QtGui.QWidget()
        self.design_tab.setObjectName(_fromUtf8("design_tab"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.design_tab)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.class1_wt_gb = QtGui.QGroupBox(self.design_tab)
        self.class1_wt_gb.setObjectName(_fromUtf8("class1_wt_gb"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.class1_wt_gb)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ds_gross_lab = QtGui.QLabel(self.class1_wt_gb)
        self.ds_gross_lab.setObjectName(_fromUtf8("ds_gross_lab"))
        self.horizontalLayout_5.addWidget(self.ds_gross_lab)
        self.ds_gross_out = QtGui.QLabel(self.class1_wt_gb)
        self.ds_gross_out.setStyleSheet(_fromUtf8("font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 75 12pt \"MS Shell Dlg 2\";"))
        self.ds_gross_out.setObjectName(_fromUtf8("ds_gross_out"))
        self.horizontalLayout_5.addWidget(self.ds_gross_out)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_7 = QtGui.QLabel(self.class1_wt_gb)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 3, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 2, 2, 1, 1)
        self.cargo_slider = QtGui.QSlider(self.class1_wt_gb)
        self.cargo_slider.setMinimumSize(QtCore.QSize(65, 0))
        self.cargo_slider.setMinimum(100)
        self.cargo_slider.setMaximum(300)
        self.cargo_slider.setSingleStep(20)
        self.cargo_slider.setProperty("value", 200)
        self.cargo_slider.setSliderPosition(200)
        self.cargo_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cargo_slider.setObjectName(_fromUtf8("cargo_slider"))
        self.gridLayout_9.addWidget(self.cargo_slider, 2, 4, 1, 1)
        self.current_cargo_wt = QtGui.QLabel(self.class1_wt_gb)
        self.current_cargo_wt.setObjectName(_fromUtf8("current_cargo_wt"))
        self.gridLayout_9.addWidget(self.current_cargo_wt, 2, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 3, 2, 1, 1)
        self.min_cargo_lab = QtGui.QLabel(self.class1_wt_gb)
        self.min_cargo_lab.setObjectName(_fromUtf8("min_cargo_lab"))
        self.gridLayout_9.addWidget(self.min_cargo_lab, 2, 3, 1, 1)
        self.max_cargo_lab = QtGui.QLabel(self.class1_wt_gb)
        self.max_cargo_lab.setObjectName(_fromUtf8("max_cargo_lab"))
        self.gridLayout_9.addWidget(self.max_cargo_lab, 2, 5, 1, 1)
        self.label = QtGui.QLabel(self.class1_wt_gb)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 1)
        self.max_pass_lab = QtGui.QLabel(self.class1_wt_gb)
        self.max_pass_lab.setObjectName(_fromUtf8("max_pass_lab"))
        self.gridLayout_9.addWidget(self.max_pass_lab, 3, 5, 1, 1)
        self.current_pass_num = QtGui.QLabel(self.class1_wt_gb)
        self.current_pass_num.setObjectName(_fromUtf8("current_pass_num"))
        self.gridLayout_9.addWidget(self.current_pass_num, 3, 1, 1, 1)
        self.min_pass_lab = QtGui.QLabel(self.class1_wt_gb)
        self.min_pass_lab.setObjectName(_fromUtf8("min_pass_lab"))
        self.gridLayout_9.addWidget(self.min_pass_lab, 3, 3, 1, 1)
        self.pass_slider = QtGui.QSlider(self.class1_wt_gb)
        self.pass_slider.setSliderPosition(10)
        self.pass_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pass_slider.setObjectName(_fromUtf8("pass_slider"))
        self.gridLayout_9.addWidget(self.pass_slider, 3, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.verticalLayout_16.addWidget(self.class1_wt_gb)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.groupBox_3 = QtGui.QGroupBox(self.design_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.plots_vlayout = QtGui.QVBoxLayout()
        self.plots_vlayout.setObjectName(_fromUtf8("plots_vlayout"))
        self.sscg_check = QtGui.QCheckBox(self.groupBox_3)
        self.sscg_check.setObjectName(_fromUtf8("sscg_check"))
        self.plots_vlayout.addWidget(self.sscg_check)
        self.missedapp_check = QtGui.QCheckBox(self.groupBox_3)
        self.missedapp_check.setObjectName(_fromUtf8("missedapp_check"))
        self.plots_vlayout.addWidget(self.missedapp_check)
        self.landing_check = QtGui.QCheckBox(self.groupBox_3)
        self.landing_check.setObjectName(_fromUtf8("landing_check"))
        self.plots_vlayout.addWidget(self.landing_check)
        self.takeoff_check = QtGui.QCheckBox(self.groupBox_3)
        self.takeoff_check.setObjectName(_fromUtf8("takeoff_check"))
        self.plots_vlayout.addWidget(self.takeoff_check)
        self.roc_check = QtGui.QCheckBox(self.groupBox_3)
        self.roc_check.setObjectName(_fromUtf8("roc_check"))
        self.plots_vlayout.addWidget(self.roc_check)
        self.stall_check = QtGui.QCheckBox(self.groupBox_3)
        self.stall_check.setObjectName(_fromUtf8("stall_check"))
        self.plots_vlayout.addWidget(self.stall_check)
        self.verticalLayout_15.addLayout(self.plots_vlayout)
        self.verticalLayout_16.addWidget(self.groupBox_3)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.groupBox_2 = QtGui.QGroupBox(self.design_tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.graphs_hlayout = QtGui.QHBoxLayout()
        self.graphs_hlayout.setObjectName(_fromUtf8("graphs_hlayout"))
        self.verticalLayout_13.addLayout(self.graphs_hlayout)

        self.pw = pg.PlotWidget(name='Constraint Analysis')  ## giving the plots names allows us to link their axes together
        self.graphs_hlayout.addWidget(self.pw)
        self.pw.setLabel('left','Thrust Loading',units = 'N/kg')
        self.pw.setLabel('bottom','Wing Loading',units = 'kg/m3')


        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.design_explore_grid = QtGui.QGridLayout()
        self.design_explore_grid.setObjectName(_fromUtf8("design_explore_grid"))
        self.takeoff_current_lab = QtGui.QLabel(self.groupBox_2)
        self.takeoff_current_lab.setObjectName(_fromUtf8("takeoff_current_lab"))
        self.design_explore_grid.addWidget(self.takeoff_current_lab, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.design_explore_grid.addWidget(self.label_3, 0, 0, 1, 1)
        self.takeoff_min_lab = QtGui.QLabel(self.groupBox_2)
        self.takeoff_min_lab.setObjectName(_fromUtf8("takeoff_min_lab"))
        self.design_explore_grid.addWidget(self.takeoff_min_lab, 0, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.design_explore_grid.addItem(spacerItem14, 0, 2, 1, 1)
        self.takeoff_slider = QtGui.QSlider(self.groupBox_2)
        self.takeoff_slider.setOrientation(QtCore.Qt.Horizontal)
        self.takeoff_slider.setObjectName(_fromUtf8("takeoff_slider"))
        self.design_explore_grid.addWidget(self.takeoff_slider, 0, 4, 1, 1)
        self.takeoff_max_lab = QtGui.QLabel(self.groupBox_2)
        self.takeoff_max_lab.setObjectName(_fromUtf8("takeoff_max_lab"))
        self.design_explore_grid.addWidget(self.takeoff_max_lab, 0, 5, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.design_explore_grid.addWidget(self.label_19, 2, 0, 1, 1)
        self.landing_current_lab = QtGui.QLabel(self.groupBox_2)
        self.landing_current_lab.setObjectName(_fromUtf8("landing_current_lab"))
        self.design_explore_grid.addWidget(self.landing_current_lab, 1, 1, 1, 1)
        self.landing_max_lab = QtGui.QLabel(self.groupBox_2)
        self.landing_max_lab.setObjectName(_fromUtf8("landing_max_lab"))
        self.design_explore_grid.addWidget(self.landing_max_lab, 1, 5, 1, 1)
        self.roc_current_lab = QtGui.QLabel(self.groupBox_2)
        self.roc_current_lab.setObjectName(_fromUtf8("roc_current_lab"))
        self.design_explore_grid.addWidget(self.roc_current_lab, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.design_explore_grid.addWidget(self.label_9, 1, 0, 1, 1)
        self.landing_min_lab = QtGui.QLabel(self.groupBox_2)
        self.landing_min_lab.setObjectName(_fromUtf8("landing_min_lab"))
        self.design_explore_grid.addWidget(self.landing_min_lab, 1, 3, 1, 1)
        self.roc_min_lab = QtGui.QLabel(self.groupBox_2)
        self.roc_min_lab.setObjectName(_fromUtf8("roc_min_lab"))
        self.design_explore_grid.addWidget(self.roc_min_lab, 2, 3, 1, 1)
        self.stall_min_lab = QtGui.QLabel(self.groupBox_2)
        self.stall_min_lab.setObjectName(_fromUtf8("stall_min_lab"))
        self.design_explore_grid.addWidget(self.stall_min_lab, 3, 3, 1, 1)
        self.roc_max_lab = QtGui.QLabel(self.groupBox_2)
        self.roc_max_lab.setObjectName(_fromUtf8("roc_max_lab"))
        self.design_explore_grid.addWidget(self.roc_max_lab, 2, 5, 1, 1)
        self.roc_slider = QtGui.QSlider(self.groupBox_2)
        self.roc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.roc_slider.setObjectName(_fromUtf8("roc_slider"))
        self.design_explore_grid.addWidget(self.roc_slider, 2, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.design_explore_grid.addWidget(self.label_24, 3, 0, 1, 1)
        self.stall_current_lab = QtGui.QLabel(self.groupBox_2)
        self.stall_current_lab.setObjectName(_fromUtf8("stall_current_lab"))
        self.design_explore_grid.addWidget(self.stall_current_lab, 3, 1, 1, 1)
        self.landing_slider = QtGui.QSlider(self.groupBox_2)
        self.landing_slider.setOrientation(QtCore.Qt.Horizontal)
        self.landing_slider.setObjectName(_fromUtf8("landing_slider"))
        self.design_explore_grid.addWidget(self.landing_slider, 1, 4, 1, 1)
        self.stall_slider = QtGui.QSlider(self.groupBox_2)
        self.stall_slider.setOrientation(QtCore.Qt.Horizontal)
        self.stall_slider.setObjectName(_fromUtf8("stall_slider"))
        self.design_explore_grid.addWidget(self.stall_slider, 3, 4, 1, 1)
        self.stall_max_lab = QtGui.QLabel(self.groupBox_2)
        self.stall_max_lab.setObjectName(_fromUtf8("stall_max_lab"))
        self.design_explore_grid.addWidget(self.stall_max_lab, 3, 5, 1, 1)
        self.horizontalLayout.addLayout(self.design_explore_grid)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.design_tab, _fromUtf8(""))
        self.fuselage_tab = QtGui.QWidget()
        self.fuselage_tab.setObjectName(_fromUtf8("fuselage_tab"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.fuselage_tab)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_15 = QtGui.QLabel(self.fuselage_tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_12.addWidget(self.label_15)
        self.comboBox_3 = QtGui.QComboBox(self.fuselage_tab)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_3)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.groupBox_4 = QtGui.QGroupBox(self.fuselage_tab)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_12.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_12.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_12.addWidget(self.label_17, 2, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_3.setMinimum(0)
        self.spinBox_3.setMaximum(12)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_12.addWidget(self.spinBox_3, 2, 3, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_4.setMinimum(0)
        self.spinBox_4.setMaximum(12)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_12.addWidget(self.spinBox_4, 2, 2, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_9.setMaximum(3)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_12.addWidget(self.spinBox_9, 3, 3, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_8.setMaximum(3)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_12.addWidget(self.spinBox_8, 3, 2, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_7.setMaximum(3)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_12.addWidget(self.spinBox_7, 3, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_2.setMinimum(0)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_12.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_5)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_12.addWidget(self.label_44, 4, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_12.addWidget(self.lineEdit_20, 4, 1, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_12.addWidget(self.lineEdit_21, 4, 2, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_12.addWidget(self.lineEdit_22, 4, 3, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_13.setMaximum(1)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_12.addWidget(self.spinBox_13, 6, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 5, 0, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_6.setMaximum(1)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_12.addWidget(self.spinBox_6, 6, 1, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_5.setMinimum(0)
        self.spinBox_5.setMaximum(2)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_12.addWidget(self.spinBox_5, 5, 1, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_11.setMaximum(2)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_12.addWidget(self.spinBox_11, 5, 3, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_10.setMaximum(2)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_12.addWidget(self.spinBox_10, 5, 2, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_12.setMaximum(1)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_12.addWidget(self.spinBox_12, 6, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_12.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_12.addWidget(self.spinBox, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_12)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_14.addWidget(self.label_33, 2, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_5)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_14)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_8.setEnabled(False)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_41 = QtGui.QLabel(self.groupBox_8)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_8.addWidget(self.label_41)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_38 = QtGui.QLabel(self.groupBox_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_15.addWidget(self.label_38, 1, 2, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_15.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_8)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_15.addWidget(self.label_35, 1, 1, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_15.addWidget(self.lineEdit_12, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_15.addWidget(self.label_34, 1, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_15.addWidget(self.lineEdit_14, 2, 2, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout_15)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(self.fuselage_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.graphicsView = QtGui.QGraphicsView(self.groupBox)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_18.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_6 = QtGui.QGroupBox(self.fuselage_tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_11.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_11.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_11.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 4, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_11.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_11.addWidget(self.label_18, 5, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_11.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_11.addWidget(self.label_21, 2, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_11.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_11.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_11.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_11.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_11.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_6)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_11.addWidget(self.label_42, 8, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_11.addWidget(self.label_25, 7, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_11.addWidget(self.lineEdit_15, 8, 1, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_11.addWidget(self.lineEdit_19, 9, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_6)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_11.addWidget(self.label_43, 9, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_6, 0, 2, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_7, 1, 2, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_8, 2, 2, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_9, 3, 2, 1, 1)
        self.comboBox_10 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_10, 4, 2, 1, 1)
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_11, 5, 2, 1, 1)
        self.comboBox_12 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_12, 6, 2, 1, 1)
        self.comboBox_13 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_13, 7, 2, 1, 1)
        self.comboBox_14 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_14.setMinimumSize(QtCore.QSize(34, 0))
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_14, 8, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_11)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.groupBox_6)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_19.addWidget(self.graphicsView_2)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout_13.addWidget(self.horizontalSlider)
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.verticalLayout_19.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_13.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_13.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_13.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_7)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_13.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_13.addWidget(self.lineEdit_16, 2, 1, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_13.addWidget(self.lineEdit_17, 4, 1, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_13.addWidget(self.lineEdit_18, 3, 1, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.comboBox_5, 4, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_7)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_13.addWidget(self.label_32, 4, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_7)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_13.addWidget(self.label_46, 3, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_7)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.comboBox_4, 1, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_13.addWidget(self.label_45, 2, 0, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_13)
        self.verticalLayout_17.addWidget(self.groupBox_7)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem17)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.pushButton = QtGui.QPushButton(self.groupBox_6)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_15.addWidget(self.pushButton)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.fuselage_tab, _fromUtf8(""))
        self.historic_tab = QtGui.QWidget()
        self.historic_tab.setObjectName(_fromUtf8("historic_tab"))
        self.tabWidget.addTab(self.historic_tab, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.performance_gb.setTitle(_translate("MainWindow", "Performance", None))
        self.roc_cels.setText(_translate("MainWindow", "C", None))
        self.roc_lab.setText(_translate("MainWindow", "Rate of Climb:", None))
        self.cruise_m_lab.setText(_translate("MainWindow", "Cruise Mach No.:", None))
        self.roc_isa.setText(_translate("MainWindow", "for ISA+", None))
        self.roc_mpers_comb.setItemText(0, _translate("MainWindow", "m/s", None))
        self.roc_mpers_comb.setItemText(1, _translate("MainWindow", "ft/min", None))
        self.ser_ceil_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.ser_ceil_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.serv_ceil_lab.setText(_translate("MainWindow", "Service Ceiling:", None))
        self.des_rang_km_comb.setItemText(0, _translate("MainWindow", "km", None))
        self.des_rang_km_comb.setItemText(1, _translate("MainWindow", "mi", None))
        self.des_rang_km_comb.setItemText(2, _translate("MainWindow", "nm", None))
        self.des_rang_lab.setText(_translate("MainWindow", "Design Range:", None))
        self.des_rang_payload_lab.setText(_translate("MainWindow", "for payload: ", None))
        self.des_rang_payload_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.des_rang_payload_kg_comb.setItemText(1, _translate("MainWindow", "lb", None))
        self.to_lan_gb.setTitle(_translate("MainWindow", "Take-off and landing", None))
        self.lan_land_lab.setText(_translate("MainWindow", "Landing Distance (Land):   ", None))
        self.lan_water_lab.setText(_translate("MainWindow", "Landing Distance (Water): ", None))
        self.max_run_alt_lab.setText(_translate("MainWindow", "Max. Runway altitude:       ", None))
        self.tod_land_lab.setText(_translate("MainWindow", "Take-off Distance (Land):  ", None))
        self.tod_water_lab.setText(_translate("MainWindow", "Take-off Distance (Water):", None))
        self.tod_lan_m_comb.setItemText(0, _translate("MainWindow", "m ", None))
        self.tod_lan_m_comb.setItemText(1, _translate("MainWindow", "ft ", None))
        self.tod_water_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.tod_water_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.lan_land_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.lan_land_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.lan_water_m_comb.setItemText(0, _translate("MainWindow", "m ", None))
        self.lan_water_m_comb.setItemText(1, _translate("MainWindow", "ft ", None))
        self.max_run_alt_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.max_run_alt_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.msl_isa.setText(_translate("MainWindow", "ISA+", None))
        self.atm_msl_lab.setText(_translate("MainWindow", "Atmospheric compliance at MSL:       ", None))
        self.label_28.setText(_translate("MainWindow", "C", None))
        self.atm_alt_lab.setText(_translate("MainWindow", "Atmospheric compliance at altitude m :", None))
        self.alt_isa.setText(_translate("MainWindow", "ISA+", None))
        self.label_29.setText(_translate("MainWindow", "C", None))
        self.turn_rate_gb.setTitle(_translate("MainWindow", "Turn Rate", None))
        self.inst_lab.setText(_translate("MainWindow", "Instantaneous: ", None))
        self.sus_degpers_comb.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.sus_degpers_comb.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.sus_lab.setText(_translate("MainWindow", "Sustained:         ", None))
        self.inst_degpers_comb.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.inst_degpers_comb.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.bank_ang_lab.setText(_translate("MainWindow", "Bank angle:       ", None))
        self.bank_ang_deg_comb.setItemText(0, _translate("MainWindow", "deg", None))
        self.bank_ang_deg_comb.setItemText(1, _translate("MainWindow", "rad", None))
        self.operational_gb.setTitle(_translate("MainWindow", "Operational", None))
        self.reg_lab.setText(_translate("MainWindow", "Aviation Regulations:", None))
        self.reg_comb.setItemText(0, _translate("MainWindow", "FAR 23", None))
        self.reg_comb.setItemText(1, _translate("MainWindow", "FAR 25", None))
        self.fuel_res_lab.setText(_translate("MainWindow", "Fuel Reserve range:", None))
        self.fuel_res_km_comb.setItemText(0, _translate("MainWindow", "km", None))
        self.fuel_res_km_comb.setItemText(1, _translate("MainWindow", "nm", None))
        self.fuel_res_km_comb.setItemText(2, _translate("MainWindow", "mi", None))
        self.payload_gb.setTitle(_translate("MainWindow", "Payload", None))
        self.pay_wt_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.cargo_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.cargo_kg_comb.setItemText(1, _translate("MainWindow", "lb", None))
        self.cargo_lab.setText(_translate("MainWindow", "Cargo Weight:", None))
        self.pay_wt_lab.setText(_translate("MainWindow", "Total Payload Weight:  ", None))
        self.pass_lab.setText(_translate("MainWindow", "Number of Passengers:", None))
        self.pay_wt_inplab.setText(_translate("MainWindow", "TextLabel", None))
        self.engine_lab.setText(_translate("MainWindow", "Number of engines", None))
        self.set_req_push.setText(_translate("MainWindow", "Set Requirements", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.req_tab), _translate("MainWindow", "Requirements", None))
        self.miss_select_comb.setItemText(0, _translate("MainWindow", "Mission 1", None))
        self.miss_add_push.setText(_translate("MainWindow", "Add", None))
        self.miss_rem_push.setText(_translate("MainWindow", "Remove", None))
        self.alt_beg_seg_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.alt_beg_seg_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.miss_nam_lab.setText(_translate("MainWindow", "Mission Name: ", None))
        self.alt_beg_lab.setText(_translate("MainWindow", "Altitude at beginning of mission:", None))
        self.seg_inf_gb.setTitle(_translate("MainWindow", "Segment info", None))
        self.typ_seg_lab.setText(_translate("MainWindow", "Type of Segment", None))
        self.rang_seg_lab.setText(_translate("MainWindow", "Range of segment:  ", None))
        self.ht_seg_lab.setText(_translate("MainWindow", "Height of segment:  ", None))
        self.typ_seg_comb.setItemText(0, _translate("MainWindow", "Takeoff", None))
        self.typ_seg_comb.setItemText(1, _translate("MainWindow", "Climb", None))
        self.typ_seg_comb.setItemText(2, _translate("MainWindow", "Cruise", None))
        self.typ_seg_comb.setItemText(3, _translate("MainWindow", "Loiter", None))
        self.typ_seg_comb.setItemText(4, _translate("MainWindow", "Descent", None))
        self.typ_seg_comb.setItemText(5, _translate("MainWindow", "Landing", None))
        self.time_seg_lab.setText(_translate("MainWindow", "Time duration        ", None))
        self.rang_seg_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.rang_seg_m_comb.setItemText(1, _translate("MainWindow", "km", None))
        self.rang_seg_m_comb.setItemText(2, _translate("MainWindow", "ft", None))
        self.ht_seg_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.ht_seg_m_comb.setItemText(1, _translate("MainWindow", "km", None))
        self.ht_seg_m_comb.setItemText(2, _translate("MainWindow", "ft", None))
        self.time_seg_hr_comb.setItemText(0, _translate("MainWindow", "hr", None))
        self.time_seg_hr_comb.setItemText(1, _translate("MainWindow", "min", None))
        self.add_seg_push.setText(_translate("MainWindow", "Add Segment", None))
        self.rem_seg_push.setText(_translate("MainWindow", "Remove Segment", None))
        self.ana_miss_push.setText(_translate("MainWindow", "Analyse Mission", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission_tab), _translate("MainWindow", "Mission Definition", None))
        self.class1_wt_gb.setTitle(_translate("MainWindow", "Class I Weight Estimation", None))
        self.ds_gross_lab.setText(_translate("MainWindow", "Gross Weight:", None))
        self.ds_gross_out.setText(_translate("MainWindow", "0", None))
        self.label_7.setText(_translate("MainWindow", "Passengers", None))
        self.current_cargo_wt.setText(_translate("MainWindow", "TextLabel", None))
        self.min_cargo_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.max_cargo_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "Cargo Weight", None))
        self.max_pass_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.current_pass_num.setText(_translate("MainWindow", "TextLabel", None))
        self.min_pass_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Design Constraints", None))
        self.sscg_check.setText(_translate("MainWindow", "Second Stage Climb Gradient", None))
        self.missedapp_check.setText(_translate("MainWindow", "Missed Approach Climb Gradient", None))
        self.landing_check.setText(_translate("MainWindow", "Landing Field Length", None))
        self.takeoff_check.setText(_translate("MainWindow", "Takeoff Ground Roll", None))
        self.roc_check.setText(_translate("MainWindow", "Rate of climb", None))
        self.stall_check.setText(_translate("MainWindow", "Stall Velocity", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox", None))
        self.takeoff_current_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "Takeoff Ground Roll", None))
        self.takeoff_min_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.takeoff_max_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.label_19.setText(_translate("MainWindow", "Rate of Climb", None))
        self.landing_current_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.landing_max_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.roc_current_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "Landing Field Length", None))
        self.landing_min_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.roc_min_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.stall_min_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.roc_max_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow", "Stall Velocity", None))
        self.stall_current_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.stall_max_lab.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.design_tab), _translate("MainWindow", "Initial SIzing", None))
        self.label_15.setText(_translate("MainWindow", "Type of Aircraft:", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Passenger", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Cargo", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cabin configuration", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Passenger", None))
        self.label_2.setText(_translate("MainWindow", "Class", None))
        self.label_16.setText(_translate("MainWindow", "III", None))
        self.label_20.setText(_translate("MainWindow", "Number of aisles:", None))
        self.label_8.setText(_translate("MainWindow", "II", None))
        self.label_4.setText(_translate("MainWindow", "I", None))
        self.label_17.setText(_translate("MainWindow", "Avg. seats abreast", None))
        self.label_44.setText(_translate("MainWindow", "Seat Pitch", None))
        self.label_14.setText(_translate("MainWindow", "Number of Lavatories: ", None))
        self.label_5.setText(_translate("MainWindow", "Number of Galleys: ", None))
        self.label_10.setText(_translate("MainWindow", "Number of classes: ", None))
        self.label_13.setText(_translate("MainWindow", "Satisfying the number of paassengers", None))
        self.label_33.setText(_translate("MainWindow", "Lower deck container", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "LD1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "LD11", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "LD2", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "LD26", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "LD29", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "LD3", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "LD3-45", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "LD3-45W", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "LD3-45(Rect)", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "LD39", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "LD4", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "LD6", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "LD7", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "LD7(Rect)", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "LD8", None))
        self.comboBox.setItemText(16, _translate("MainWindow", "LD9", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Cargo", None))
        self.label_41.setText(_translate("MainWindow", "Cargo bay dimensions", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_38.setText(_translate("MainWindow", "Height", None))
        self.label_35.setText(_translate("MainWindow", "Width", None))
        self.label_34.setText(_translate("MainWindow", "Length", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Cross-section", None))
        self.label_12.setText(_translate("MainWindow", "Floor Thickness", None))
        self.label_11.setText(_translate("MainWindow", "Inner height", None))
        self.label_6.setText(_translate("MainWindow", "Floor lowering from \n"
"fuselage symmetry", None))
        self.label_23.setText(_translate("MainWindow", "Fuselage Thickness", None))
        self.label_22.setText(_translate("MainWindow", "Inner equivalent \n"
"diameter", None))
        self.label_18.setText(_translate("MainWindow", "Outer equivalent \n"
"diameter", None))
        self.label_21.setText(_translate("MainWindow", "Inner width", None))
        self.label_42.setText(_translate("MainWindow", "Outer Width", None))
        self.label_25.setText(_translate("MainWindow", "Outer Height", None))
        self.label_43.setText(_translate("MainWindow", "Cabin height to \n"
"weight ratio", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "ft", None))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_14.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_27.setText(_translate("MainWindow", "0.7", None))
        self.label_26.setText(_translate("MainWindow", "1.3", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Length", None))
        self.label_30.setText(_translate("MainWindow", "Nose length to diameter ratio", None))
        self.label_31.setText(_translate("MainWindow", "Nose offset", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_32.setText(_translate("MainWindow", "Cabin Length", None))
        self.label_46.setText(_translate("MainWindow", "Tail offset to diameter ratio", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ft", None))
        self.label_45.setText(_translate("MainWindow", "Tail length to diameter ratio", None))
        self.pushButton.setText(_translate("MainWindow", "Set Fuselage parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fuselage_tab), _translate("MainWindow", "Fuselage Config", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historic_tab), _translate("MainWindow", "Historic Data", None))

