# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window3.ui'
#
# Created: Sun Feb 22 01:29:22 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(773, 571)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.req_tab = QtGui.QWidget()
        self.req_tab.setObjectName(_fromUtf8("req_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.req_tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.performance_gb = QtGui.QGroupBox(self.req_tab)
        self.performance_gb.setObjectName(_fromUtf8("performance_gb"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.performance_gb)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.roc_cels = QtGui.QLabel(self.performance_gb)
        self.roc_cels.setObjectName(_fromUtf8("roc_cels"))
        self.gridLayout_3.addWidget(self.roc_cels, 2, 5, 1, 1)
        self.roc_lab = QtGui.QLabel(self.performance_gb)
        self.roc_lab.setObjectName(_fromUtf8("roc_lab"))
        self.gridLayout_3.addWidget(self.roc_lab, 2, 0, 1, 1)
        self.cruise_m_lab = QtGui.QLabel(self.performance_gb)
        self.cruise_m_lab.setObjectName(_fromUtf8("cruise_m_lab"))
        self.gridLayout_3.addWidget(self.cruise_m_lab, 3, 0, 1, 1)
        self.cruise_m_inp = QtGui.QLineEdit(self.performance_gb)
        self.cruise_m_inp.setObjectName(_fromUtf8("cruise_m_inp"))
        self.gridLayout_3.addWidget(self.cruise_m_inp, 3, 1, 1, 1)
        self.roc_isa = QtGui.QLabel(self.performance_gb)
        self.roc_isa.setObjectName(_fromUtf8("roc_isa"))
        self.gridLayout_3.addWidget(self.roc_isa, 2, 3, 1, 1)
        self.roc_isa_t_sb = QtGui.QSpinBox(self.performance_gb)
        self.roc_isa_t_sb.setMaximum(100)
        self.roc_isa_t_sb.setSingleStep(5)
        self.roc_isa_t_sb.setObjectName(_fromUtf8("roc_isa_t_sb"))
        self.gridLayout_3.addWidget(self.roc_isa_t_sb, 2, 4, 1, 1)
        self.roc_mpers_comb = QtGui.QComboBox(self.performance_gb)
        self.roc_mpers_comb.setObjectName(_fromUtf8("roc_mpers_comb"))
        self.roc_mpers_comb.addItem(_fromUtf8(""))
        self.roc_mpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.roc_mpers_comb, 2, 2, 1, 1)
        self.serv_ceil_inp = QtGui.QLineEdit(self.performance_gb)
        self.serv_ceil_inp.setObjectName(_fromUtf8("serv_ceil_inp"))
        self.gridLayout_3.addWidget(self.serv_ceil_inp, 1, 1, 1, 1)
        self.roc_inp = QtGui.QLineEdit(self.performance_gb)
        self.roc_inp.setObjectName(_fromUtf8("roc_inp"))
        self.gridLayout_3.addWidget(self.roc_inp, 2, 1, 1, 1)
        self.ser_ceil_m_comb = QtGui.QComboBox(self.performance_gb)
        self.ser_ceil_m_comb.setObjectName(_fromUtf8("ser_ceil_m_comb"))
        self.ser_ceil_m_comb.addItem(_fromUtf8(""))
        self.ser_ceil_m_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ser_ceil_m_comb, 1, 2, 1, 1)
        self.des_rang_payload_inp = QtGui.QLineEdit(self.performance_gb)
        self.des_rang_payload_inp.setObjectName(_fromUtf8("des_rang_payload_inp"))
        self.gridLayout_3.addWidget(self.des_rang_payload_inp, 0, 4, 1, 1)
        self.serv_ceil_lab = QtGui.QLabel(self.performance_gb)
        self.serv_ceil_lab.setObjectName(_fromUtf8("serv_ceil_lab"))
        self.gridLayout_3.addWidget(self.serv_ceil_lab, 1, 0, 1, 1)
        self.des_rang_km_comb = QtGui.QComboBox(self.performance_gb)
        self.des_rang_km_comb.setObjectName(_fromUtf8("des_rang_km_comb"))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.des_rang_km_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.des_rang_km_comb, 0, 2, 1, 1)
        self.des_rang_inp = QtGui.QLineEdit(self.performance_gb)
        self.des_rang_inp.setObjectName(_fromUtf8("des_rang_inp"))
        self.gridLayout_3.addWidget(self.des_rang_inp, 0, 1, 1, 1)
        self.des_rang_lab = QtGui.QLabel(self.performance_gb)
        self.des_rang_lab.setObjectName(_fromUtf8("des_rang_lab"))
        self.gridLayout_3.addWidget(self.des_rang_lab, 0, 0, 1, 1)
        self.des_rang_payload_lab = QtGui.QLabel(self.performance_gb)
        self.des_rang_payload_lab.setObjectName(_fromUtf8("des_rang_payload_lab"))
        self.gridLayout_3.addWidget(self.des_rang_payload_lab, 0, 3, 1, 1)
        self.des_rang_payload_kg_comb = QtGui.QComboBox(self.performance_gb)
        self.des_rang_payload_kg_comb.setObjectName(_fromUtf8("des_rang_payload_kg_comb"))
        self.des_rang_payload_kg_comb.addItem(_fromUtf8(""))
        self.des_rang_payload_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.des_rang_payload_kg_comb, 0, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.to_lan_gb = QtGui.QGroupBox(self.performance_gb)
        self.to_lan_gb.setObjectName(_fromUtf8("to_lan_gb"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.to_lan_gb)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_40 = QtGui.QLabel(self.to_lan_gb)
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 2, 1, 1, 1)
        self.lan_land_lab = QtGui.QLabel(self.to_lan_gb)
        self.lan_land_lab.setObjectName(_fromUtf8("lan_land_lab"))
        self.gridLayout.addWidget(self.lan_land_lab, 2, 0, 1, 1)
        self.max_run_alt_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.max_run_alt_inp.setObjectName(_fromUtf8("max_run_alt_inp"))
        self.gridLayout.addWidget(self.max_run_alt_inp, 4, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.to_lan_gb)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 3, 1, 1, 1)
        self.lan_water_lab = QtGui.QLabel(self.to_lan_gb)
        self.lan_water_lab.setObjectName(_fromUtf8("lan_water_lab"))
        self.gridLayout.addWidget(self.lan_water_lab, 3, 0, 1, 1)
        self.lan_land_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.lan_land_inp.setObjectName(_fromUtf8("lan_land_inp"))
        self.gridLayout.addWidget(self.lan_land_inp, 2, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.to_lan_gb)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 0, 1, 1, 1)
        self.lan_water_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.lan_water_inp.setObjectName(_fromUtf8("lan_water_inp"))
        self.gridLayout.addWidget(self.lan_water_inp, 3, 4, 1, 1)
        self.max_run_alt_lab = QtGui.QLabel(self.to_lan_gb)
        self.max_run_alt_lab.setObjectName(_fromUtf8("max_run_alt_lab"))
        self.gridLayout.addWidget(self.max_run_alt_lab, 4, 0, 1, 1)
        self.tod_land_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.tod_land_inp.setObjectName(_fromUtf8("tod_land_inp"))
        self.gridLayout.addWidget(self.tod_land_inp, 0, 4, 1, 1)
        self.tod_land_lab = QtGui.QLabel(self.to_lan_gb)
        self.tod_land_lab.setObjectName(_fromUtf8("tod_land_lab"))
        self.gridLayout.addWidget(self.tod_land_lab, 0, 0, 1, 1)
        self.tod_water_lab = QtGui.QLabel(self.to_lan_gb)
        self.tod_water_lab.setObjectName(_fromUtf8("tod_water_lab"))
        self.gridLayout.addWidget(self.tod_water_lab, 1, 0, 1, 1)
        self.tod_water_inp = QtGui.QLineEdit(self.to_lan_gb)
        self.tod_water_inp.setObjectName(_fromUtf8("tod_water_inp"))
        self.gridLayout.addWidget(self.tod_water_inp, 1, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.to_lan_gb)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 1, 1, 1, 1)
        self.tod_lan_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.tod_lan_m_comb.setObjectName(_fromUtf8("tod_lan_m_comb"))
        self.tod_lan_m_comb.addItem(_fromUtf8(""))
        self.tod_lan_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.tod_lan_m_comb, 0, 5, 1, 1)
        self.tod_water_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.tod_water_m_comb.setObjectName(_fromUtf8("tod_water_m_comb"))
        self.tod_water_m_comb.addItem(_fromUtf8(""))
        self.tod_water_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.tod_water_m_comb, 1, 5, 1, 1)
        self.lan_land_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.lan_land_m_comb.setObjectName(_fromUtf8("lan_land_m_comb"))
        self.lan_land_m_comb.addItem(_fromUtf8(""))
        self.lan_land_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.lan_land_m_comb, 2, 5, 1, 1)
        self.lan_water_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.lan_water_m_comb.setObjectName(_fromUtf8("lan_water_m_comb"))
        self.lan_water_m_comb.addItem(_fromUtf8(""))
        self.lan_water_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.lan_water_m_comb, 3, 5, 1, 1)
        self.max_run_alt_m_comb = QtGui.QComboBox(self.to_lan_gb)
        self.max_run_alt_m_comb.setObjectName(_fromUtf8("max_run_alt_m_comb"))
        self.max_run_alt_m_comb.addItem(_fromUtf8(""))
        self.max_run_alt_m_comb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.max_run_alt_m_comb, 4, 5, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.msl_isa = QtGui.QLabel(self.to_lan_gb)
        self.msl_isa.setObjectName(_fromUtf8("msl_isa"))
        self.gridLayout_2.addWidget(self.msl_isa, 0, 1, 1, 1)
        self.atm_msl_lab = QtGui.QLabel(self.to_lan_gb)
        self.atm_msl_lab.setObjectName(_fromUtf8("atm_msl_lab"))
        self.gridLayout_2.addWidget(self.atm_msl_lab, 0, 0, 1, 1)
        self.run_msl_isa_t_sb = QtGui.QSpinBox(self.to_lan_gb)
        self.run_msl_isa_t_sb.setMaximum(100)
        self.run_msl_isa_t_sb.setSingleStep(5)
        self.run_msl_isa_t_sb.setObjectName(_fromUtf8("run_msl_isa_t_sb"))
        self.gridLayout_2.addWidget(self.run_msl_isa_t_sb, 0, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.to_lan_gb)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.atm_alt_lab = QtGui.QLabel(self.to_lan_gb)
        self.atm_alt_lab.setObjectName(_fromUtf8("atm_alt_lab"))
        self.gridLayout_2.addWidget(self.atm_alt_lab, 1, 0, 1, 1)
        self.alt_isa = QtGui.QLabel(self.to_lan_gb)
        self.alt_isa.setObjectName(_fromUtf8("alt_isa"))
        self.gridLayout_2.addWidget(self.alt_isa, 1, 1, 1, 1)
        self.run_alt_isa_t_sb = QtGui.QSpinBox(self.to_lan_gb)
        self.run_alt_isa_t_sb.setMaximum(100)
        self.run_alt_isa_t_sb.setSingleStep(5)
        self.run_alt_isa_t_sb.setObjectName(_fromUtf8("run_alt_isa_t_sb"))
        self.gridLayout_2.addWidget(self.run_alt_isa_t_sb, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.to_lan_gb)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_10.addWidget(self.to_lan_gb)
        self.turn_rate_gb = QtGui.QGroupBox(self.performance_gb)
        self.turn_rate_gb.setObjectName(_fromUtf8("turn_rate_gb"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.turn_rate_gb)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.inst_lab = QtGui.QLabel(self.turn_rate_gb)
        self.inst_lab.setObjectName(_fromUtf8("inst_lab"))
        self.gridLayout_4.addWidget(self.inst_lab, 0, 0, 1, 1)
        self.sus_degpers_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.sus_degpers_comb.setObjectName(_fromUtf8("sus_degpers_comb"))
        self.sus_degpers_comb.addItem(_fromUtf8(""))
        self.sus_degpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.sus_degpers_comb, 1, 2, 1, 1)
        self.sus_lab = QtGui.QLabel(self.turn_rate_gb)
        self.sus_lab.setObjectName(_fromUtf8("sus_lab"))
        self.gridLayout_4.addWidget(self.sus_lab, 1, 0, 1, 1)
        self.inst_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.inst_inp.setObjectName(_fromUtf8("inst_inp"))
        self.gridLayout_4.addWidget(self.inst_inp, 0, 1, 1, 1)
        self.inst_degpers_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.inst_degpers_comb.setObjectName(_fromUtf8("inst_degpers_comb"))
        self.inst_degpers_comb.addItem(_fromUtf8(""))
        self.inst_degpers_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.inst_degpers_comb, 0, 2, 1, 1)
        self.sus_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.sus_inp.setObjectName(_fromUtf8("sus_inp"))
        self.gridLayout_4.addWidget(self.sus_inp, 1, 1, 1, 1)
        self.bank_ang_lab = QtGui.QLabel(self.turn_rate_gb)
        self.bank_ang_lab.setObjectName(_fromUtf8("bank_ang_lab"))
        self.gridLayout_4.addWidget(self.bank_ang_lab, 2, 0, 1, 1)
        self.bank_ang_deg_comb = QtGui.QComboBox(self.turn_rate_gb)
        self.bank_ang_deg_comb.setObjectName(_fromUtf8("bank_ang_deg_comb"))
        self.bank_ang_deg_comb.addItem(_fromUtf8(""))
        self.bank_ang_deg_comb.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.bank_ang_deg_comb, 2, 2, 1, 1)
        self.bank_ang_inp = QtGui.QLineEdit(self.turn_rate_gb)
        self.bank_ang_inp.setObjectName(_fromUtf8("bank_ang_inp"))
        self.gridLayout_4.addWidget(self.bank_ang_inp, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.verticalLayout_10.addWidget(self.turn_rate_gb)
        self.verticalLayout_6.addWidget(self.performance_gb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.operational_gb = QtGui.QGroupBox(self.req_tab)
        self.operational_gb.setObjectName(_fromUtf8("operational_gb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.operational_gb)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.reg_lab = QtGui.QLabel(self.operational_gb)
        self.reg_lab.setObjectName(_fromUtf8("reg_lab"))
        self.gridLayout_6.addWidget(self.reg_lab, 0, 0, 1, 1)
        self.reg_comb = QtGui.QComboBox(self.operational_gb)
        self.reg_comb.setObjectName(_fromUtf8("reg_comb"))
        self.reg_comb.addItem(_fromUtf8(""))
        self.reg_comb.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.reg_comb, 0, 1, 1, 1)
        self.fuel_res_lab = QtGui.QLabel(self.operational_gb)
        self.fuel_res_lab.setObjectName(_fromUtf8("fuel_res_lab"))
        self.gridLayout_6.addWidget(self.fuel_res_lab, 1, 0, 1, 1)
        self.fuel_res_km_comb = QtGui.QComboBox(self.operational_gb)
        self.fuel_res_km_comb.setObjectName(_fromUtf8("fuel_res_km_comb"))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.fuel_res_km_comb.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.fuel_res_km_comb, 1, 2, 1, 1)
        self.fuel_res_inp = QtGui.QLineEdit(self.operational_gb)
        self.fuel_res_inp.setObjectName(_fromUtf8("fuel_res_inp"))
        self.gridLayout_6.addWidget(self.fuel_res_inp, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.payload_gb = QtGui.QGroupBox(self.operational_gb)
        self.payload_gb.setObjectName(_fromUtf8("payload_gb"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.payload_gb)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pay_wt_kg_comb = QtGui.QComboBox(self.payload_gb)
        self.pay_wt_kg_comb.setObjectName(_fromUtf8("pay_wt_kg_comb"))
        self.pay_wt_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pay_wt_kg_comb, 2, 2, 1, 1)
        self.cargo_kg_comb = QtGui.QComboBox(self.payload_gb)
        self.cargo_kg_comb.setObjectName(_fromUtf8("cargo_kg_comb"))
        self.cargo_kg_comb.addItem(_fromUtf8(""))
        self.cargo_kg_comb.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cargo_kg_comb, 1, 2, 1, 1)
        self.cargo_lab = QtGui.QLabel(self.payload_gb)
        self.cargo_lab.setObjectName(_fromUtf8("cargo_lab"))
        self.gridLayout_5.addWidget(self.cargo_lab, 1, 0, 1, 1)
        self.cargo_inp = QtGui.QLineEdit(self.payload_gb)
        self.cargo_inp.setObjectName(_fromUtf8("cargo_inp"))
        self.gridLayout_5.addWidget(self.cargo_inp, 1, 1, 1, 1)
        self.pay_wt_lab = QtGui.QLabel(self.payload_gb)
        self.pay_wt_lab.setObjectName(_fromUtf8("pay_wt_lab"))
        self.gridLayout_5.addWidget(self.pay_wt_lab, 2, 0, 1, 1)
        self.pass_inp = QtGui.QLineEdit(self.payload_gb)
        self.pass_inp.setObjectName(_fromUtf8("pass_inp"))
        self.gridLayout_5.addWidget(self.pass_inp, 0, 1, 1, 1)
        self.pass_lab = QtGui.QLabel(self.payload_gb)
        self.pass_lab.setObjectName(_fromUtf8("pass_lab"))
        self.gridLayout_5.addWidget(self.pass_lab, 0, 0, 1, 1)
        self.pay_wt_inplab = QtGui.QLabel(self.payload_gb)
        self.pay_wt_inplab.setObjectName(_fromUtf8("pay_wt_inplab"))
        self.gridLayout_5.addWidget(self.pay_wt_inplab, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addWidget(self.payload_gb)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.set_req_push = QtGui.QPushButton(self.operational_gb)
        self.set_req_push.setObjectName(_fromUtf8("set_req_push"))
        self.verticalLayout_2.addWidget(self.set_req_push)
        self.horizontalLayout_3.addWidget(self.operational_gb)
        self.tabWidget.addTab(self.req_tab, _fromUtf8(""))
        self.mission_tab = QtGui.QWidget()
        self.mission_tab.setObjectName(_fromUtf8("mission_tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.mission_tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.miss_select_comb = QtGui.QComboBox(self.mission_tab)
        self.miss_select_comb.setObjectName(_fromUtf8("miss_select_comb"))
        self.miss_select_comb.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.miss_select_comb)
        self.miss_add_push = QtGui.QPushButton(self.mission_tab)
        self.miss_add_push.setObjectName(_fromUtf8("miss_add_push"))
        self.horizontalLayout_2.addWidget(self.miss_add_push)
        self.miss_rem_push = QtGui.QPushButton(self.mission_tab)
        self.miss_rem_push.setObjectName(_fromUtf8("miss_rem_push"))
        self.horizontalLayout_2.addWidget(self.miss_rem_push)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_18 = QtGui.QComboBox(self.mission_tab)
        self.comboBox_18.setObjectName(_fromUtf8("comboBox_18"))
        self.comboBox_18.addItem(_fromUtf8(""))
        self.comboBox_18.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_18, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 3, 1, 1)
        self.miss_nam_lab = QtGui.QLabel(self.mission_tab)
        self.miss_nam_lab.setObjectName(_fromUtf8("miss_nam_lab"))
        self.gridLayout_7.addWidget(self.miss_nam_lab, 0, 0, 1, 1)
        self.alt_beg_inp = QtGui.QLineEdit(self.mission_tab)
        self.alt_beg_inp.setObjectName(_fromUtf8("alt_beg_inp"))
        self.gridLayout_7.addWidget(self.alt_beg_inp, 2, 1, 1, 1)
        self.miss_nam_inp = QtGui.QLineEdit(self.mission_tab)
        self.miss_nam_inp.setObjectName(_fromUtf8("miss_nam_inp"))
        self.gridLayout_7.addWidget(self.miss_nam_inp, 0, 1, 1, 1)
        self.num_miss_lab = QtGui.QLabel(self.mission_tab)
        self.num_miss_lab.setObjectName(_fromUtf8("num_miss_lab"))
        self.gridLayout_7.addWidget(self.num_miss_lab, 1, 0, 1, 1)
        self.num_miss_inp = QtGui.QLineEdit(self.mission_tab)
        self.num_miss_inp.setObjectName(_fromUtf8("num_miss_inp"))
        self.gridLayout_7.addWidget(self.num_miss_inp, 1, 1, 1, 1)
        self.alt_beg_lab = QtGui.QLabel(self.mission_tab)
        self.alt_beg_lab.setObjectName(_fromUtf8("alt_beg_lab"))
        self.gridLayout_7.addWidget(self.alt_beg_lab, 2, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_7)
        self.seg_inf_gb = QtGui.QGroupBox(self.mission_tab)
        self.seg_inf_gb.setObjectName(_fromUtf8("seg_inf_gb"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.seg_inf_gb)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.segment_info_grid1 = QtGui.QGridLayout()
        self.segment_info_grid1.setObjectName(_fromUtf8("segment_info_grid1"))
        self.typ_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.typ_seg_lab.setObjectName(_fromUtf8("typ_seg_lab"))
        self.segment_info_grid1.addWidget(self.typ_seg_lab, 0, 0, 1, 1)
        self.ht_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.ht_seg_inp.setObjectName(_fromUtf8("ht_seg_inp"))
        self.segment_info_grid1.addWidget(self.ht_seg_inp, 2, 1, 1, 1)
        self.rang_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.rang_seg_lab.setObjectName(_fromUtf8("rang_seg_lab"))
        self.segment_info_grid1.addWidget(self.rang_seg_lab, 1, 0, 1, 1)
        self.ht_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.ht_seg_lab.setObjectName(_fromUtf8("ht_seg_lab"))
        self.segment_info_grid1.addWidget(self.ht_seg_lab, 2, 0, 1, 1)
        self.typ_seg_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.typ_seg_comb.setObjectName(_fromUtf8("typ_seg_comb"))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.typ_seg_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.typ_seg_comb, 0, 1, 1, 1)
        self.time_seg_lab = QtGui.QLabel(self.seg_inf_gb)
        self.time_seg_lab.setObjectName(_fromUtf8("time_seg_lab"))
        self.segment_info_grid1.addWidget(self.time_seg_lab, 3, 0, 1, 1)
        self.time_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.time_seg_inp.setObjectName(_fromUtf8("time_seg_inp"))
        self.segment_info_grid1.addWidget(self.time_seg_inp, 3, 1, 1, 1)
        self.rang_seg_inp = QtGui.QLineEdit(self.seg_inf_gb)
        self.rang_seg_inp.setObjectName(_fromUtf8("rang_seg_inp"))
        self.segment_info_grid1.addWidget(self.rang_seg_inp, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.segment_info_grid1.addItem(spacerItem5, 0, 3, 1, 1)
        self.rang_seg_m_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.rang_seg_m_comb.setObjectName(_fromUtf8("rang_seg_m_comb"))
        self.rang_seg_m_comb.addItem(_fromUtf8(""))
        self.rang_seg_m_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.rang_seg_m_comb, 1, 2, 1, 1)
        self.ht_seg_m_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.ht_seg_m_comb.setObjectName(_fromUtf8("ht_seg_m_comb"))
        self.ht_seg_m_comb.addItem(_fromUtf8(""))
        self.ht_seg_m_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.ht_seg_m_comb, 2, 2, 1, 1)
        self.time_seg_hr_comb = QtGui.QComboBox(self.seg_inf_gb)
        self.time_seg_hr_comb.setObjectName(_fromUtf8("time_seg_hr_comb"))
        self.time_seg_hr_comb.addItem(_fromUtf8(""))
        self.time_seg_hr_comb.addItem(_fromUtf8(""))
        self.segment_info_grid1.addWidget(self.time_seg_hr_comb, 3, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.segment_info_grid1)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.add_seg_push = QtGui.QPushButton(self.seg_inf_gb)
        self.add_seg_push.setObjectName(_fromUtf8("add_seg_push"))
        self.horizontalLayout_50.addWidget(self.add_seg_push)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_50)
        self.verticalLayout_11.addWidget(self.seg_inf_gb)
        self.mission_graphics = QtGui.QGraphicsView(self.mission_tab)
        self.mission_graphics.setObjectName(_fromUtf8("mission_graphics"))
        self.verticalLayout_11.addWidget(self.mission_graphics)
        self.tabWidget.addTab(self.mission_tab, _fromUtf8(""))
        self.aircraft_tab = QtGui.QWidget()
        self.aircraft_tab.setObjectName(_fromUtf8("aircraft_tab"))
        self.groupBox_4 = QtGui.QGroupBox(self.aircraft_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 110, 235, 240))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.spinBox = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox.setMinimum(0)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_11.addWidget(self.spinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_27.addWidget(self.label_20)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_7.setMaximum(3)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_27.addWidget(self.spinBox_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_16.addWidget(self.label_6)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_16.addWidget(self.label_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_2.setMinimum(0)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_13.addWidget(self.spinBox_2)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_3.setMinimum(0)
        self.spinBox_3.setMaximum(12)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_13.addWidget(self.spinBox_3)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_4.setMinimum(0)
        self.spinBox_4.setMaximum(12)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_13.addWidget(self.spinBox_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_5.setMinimum(0)
        self.spinBox_5.setMaximum(5)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_18.addWidget(self.spinBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_6.setMaximum(3)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_8.addWidget(self.spinBox_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.label_15 = QtGui.QLabel(self.aircraft_tab)
        self.label_15.setGeometry(QtCore.QRect(210, 120, 102, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox_3 = QtGui.QComboBox(self.aircraft_tab)
        self.comboBox_3.setGeometry(QtCore.QRect(318, 120, 84, 20))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.aircraft_tab, _fromUtf8(""))
        self.design_tab = QtGui.QWidget()
        self.design_tab.setObjectName(_fromUtf8("design_tab"))
        self.tabWidget.addTab(self.design_tab, _fromUtf8(""))
        self.historic_tab = QtGui.QWidget()
        self.historic_tab.setObjectName(_fromUtf8("historic_tab"))
        self.tabWidget.addTab(self.historic_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.performance_gb.setTitle(_translate("MainWindow", "Performance", None))
        self.roc_cels.setText(_translate("MainWindow", "C", None))
        self.roc_lab.setText(_translate("MainWindow", "Rate of Climb:", None))
        self.cruise_m_lab.setText(_translate("MainWindow", "Cruise Mach No.:", None))
        self.roc_isa.setText(_translate("MainWindow", "for ISA+", None))
        self.roc_mpers_comb.setItemText(0, _translate("MainWindow", "m/s", None))
        self.roc_mpers_comb.setItemText(1, _translate("MainWindow", "ft/min", None))
        self.ser_ceil_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.ser_ceil_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.serv_ceil_lab.setText(_translate("MainWindow", "Service Ceiling:", None))
        self.des_rang_km_comb.setItemText(0, _translate("MainWindow", "km", None))
        self.des_rang_km_comb.setItemText(1, _translate("MainWindow", "mi", None))
        self.des_rang_km_comb.setItemText(2, _translate("MainWindow", "nm", None))
        self.des_rang_lab.setText(_translate("MainWindow", "Design Range:", None))
        self.des_rang_payload_lab.setText(_translate("MainWindow", "for payload: ", None))
        self.des_rang_payload_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.des_rang_payload_kg_comb.setItemText(1, _translate("MainWindow", "lb", None))
        self.to_lan_gb.setTitle(_translate("MainWindow", "Take-off and landing", None))
        self.lan_land_lab.setText(_translate("MainWindow", "Landing Distance (Land):   ", None))
        self.lan_water_lab.setText(_translate("MainWindow", "Landing Distance (Water): ", None))
        self.max_run_alt_lab.setText(_translate("MainWindow", "Max. Runway altitude:       ", None))
        self.tod_land_lab.setText(_translate("MainWindow", "Take-off Distance (Land):  ", None))
        self.tod_water_lab.setText(_translate("MainWindow", "Take-off Distance (Water):", None))
        self.tod_lan_m_comb.setItemText(0, _translate("MainWindow", "m ", None))
        self.tod_lan_m_comb.setItemText(1, _translate("MainWindow", "ft ", None))
        self.tod_water_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.tod_water_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.lan_land_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.lan_land_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.lan_water_m_comb.setItemText(0, _translate("MainWindow", "m ", None))
        self.lan_water_m_comb.setItemText(1, _translate("MainWindow", "ft ", None))
        self.max_run_alt_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.max_run_alt_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.msl_isa.setText(_translate("MainWindow", "ISA+", None))
        self.atm_msl_lab.setText(_translate("MainWindow", "Atmospheric compliance at MSL:       ", None))
        self.label_28.setText(_translate("MainWindow", "C", None))
        self.atm_alt_lab.setText(_translate("MainWindow", "Atmospheric compliance at altitude m :", None))
        self.alt_isa.setText(_translate("MainWindow", "ISA+", None))
        self.label_29.setText(_translate("MainWindow", "C", None))
        self.turn_rate_gb.setTitle(_translate("MainWindow", "Turn Rate", None))
        self.inst_lab.setText(_translate("MainWindow", "Instantaneous: ", None))
        self.sus_degpers_comb.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.sus_degpers_comb.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.sus_lab.setText(_translate("MainWindow", "Sustained:         ", None))
        self.inst_degpers_comb.setItemText(0, _translate("MainWindow", "deg/s", None))
        self.inst_degpers_comb.setItemText(1, _translate("MainWindow", "rad/s", None))
        self.bank_ang_lab.setText(_translate("MainWindow", "Bank angle:       ", None))
        self.bank_ang_deg_comb.setItemText(0, _translate("MainWindow", "deg", None))
        self.bank_ang_deg_comb.setItemText(1, _translate("MainWindow", "rad", None))
        self.operational_gb.setTitle(_translate("MainWindow", "Operational", None))
        self.reg_lab.setText(_translate("MainWindow", "Aviation Regulations:", None))
        self.reg_comb.setItemText(0, _translate("MainWindow", "FAR 23", None))
        self.reg_comb.setItemText(1, _translate("MainWindow", "FAR 25", None))
        self.fuel_res_lab.setText(_translate("MainWindow", "Fuel Reserve range:", None))
        self.fuel_res_km_comb.setItemText(0, _translate("MainWindow", "km", None))
        self.fuel_res_km_comb.setItemText(1, _translate("MainWindow", "nm", None))
        self.fuel_res_km_comb.setItemText(2, _translate("MainWindow", "mi", None))
        self.payload_gb.setTitle(_translate("MainWindow", "Payload", None))
        self.pay_wt_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.cargo_kg_comb.setItemText(0, _translate("MainWindow", "kg", None))
        self.cargo_kg_comb.setItemText(1, _translate("MainWindow", "lb", None))
        self.cargo_lab.setText(_translate("MainWindow", "Cargo Weight:", None))
        self.pay_wt_lab.setText(_translate("MainWindow", "Total Payload Weight:  ", None))
        self.pass_lab.setText(_translate("MainWindow", "Number of Passengers:", None))
        self.pay_wt_inplab.setText(_translate("MainWindow", "TextLabel", None))
        self.set_req_push.setText(_translate("MainWindow", "Set Requirements", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.req_tab), _translate("MainWindow", "Requirements", None))
        self.miss_select_comb.setItemText(0, _translate("MainWindow", "Mission 1", None))
        self.miss_add_push.setText(_translate("MainWindow", "Add", None))
        self.miss_rem_push.setText(_translate("MainWindow", "Remove", None))
        self.comboBox_18.setItemText(0, _translate("MainWindow", "m", None))
        self.comboBox_18.setItemText(1, _translate("MainWindow", "ft", None))
        self.miss_nam_lab.setText(_translate("MainWindow", "Mission Name: ", None))
        self.num_miss_lab.setText(_translate("MainWindow", "Number of mission segments:", None))
        self.alt_beg_lab.setText(_translate("MainWindow", "Altitude at beginning of mission:", None))
        self.seg_inf_gb.setTitle(_translate("MainWindow", "Segment info", None))
        self.typ_seg_lab.setText(_translate("MainWindow", "Type of Segment", None))
        self.rang_seg_lab.setText(_translate("MainWindow", "Range of segment:  ", None))
        self.ht_seg_lab.setText(_translate("MainWindow", "Height of segment:  ", None))
        self.typ_seg_comb.setItemText(0, _translate("MainWindow", "Takeoff", None))
        self.typ_seg_comb.setItemText(1, _translate("MainWindow", "Climb", None))
        self.typ_seg_comb.setItemText(2, _translate("MainWindow", "Cruise", None))
        self.typ_seg_comb.setItemText(3, _translate("MainWindow", "Loiter", None))
        self.typ_seg_comb.setItemText(4, _translate("MainWindow", "Descent", None))
        self.typ_seg_comb.setItemText(5, _translate("MainWindow", "Landing", None))
        self.time_seg_lab.setText(_translate("MainWindow", "Time duration        ", None))
        self.rang_seg_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.rang_seg_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.ht_seg_m_comb.setItemText(0, _translate("MainWindow", "m", None))
        self.ht_seg_m_comb.setItemText(1, _translate("MainWindow", "ft", None))
        self.time_seg_hr_comb.setItemText(0, _translate("MainWindow", "hr", None))
        self.time_seg_hr_comb.setItemText(1, _translate("MainWindow", "min", None))
        self.add_seg_push.setText(_translate("MainWindow", "Add Segment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mission_tab), _translate("MainWindow", "Mission Definition", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cabin configuration", None))
        self.label_10.setText(_translate("MainWindow", "Number of classes: ", None))
        self.label_20.setText(_translate("MainWindow", "Number of aisles:                        ", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Average Seats abreast", None))
        self.label_6.setText(_translate("MainWindow", "Class I", None))
        self.label_11.setText(_translate("MainWindow", "Class II", None))
        self.label_12.setText(_translate("MainWindow", "Class III", None))
        self.label_13.setText(_translate("MainWindow", "Satisfying the number of paassengers", None))
        self.label_14.setText(_translate("MainWindow", "Number of Lavatories: ", None))
        self.label_5.setText(_translate("MainWindow", "Number of Galleys: ", None))
        self.label_15.setText(_translate("MainWindow", "Type of Aircraft:", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Passenger", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Cargo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aircraft_tab), _translate("MainWindow", "Aircraft Configuration", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.design_tab), _translate("MainWindow", "Design Space", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historic_tab), _translate("MainWindow", "Historic Data", None))

